### PR TITLE
ensure that parsing of unspported strings always raises an error

### PR DESCRIPTION
**Pull request by rapimo**
currently when string input parsing enters the code path
get_device_type_num_p, get_device_type_num_s, get_device_type_num_t
or check_device_type_num an erroneous string will enter the system
as `0` resulting in a binary representation that can never be converted
back to string.

### CODE REVIEW

**Comment by zeitgeist** [comment]
`check_device_type_num` contains the error handling, too, which I'd rather try to factor our.

For instance through changing the following function to this:
```
static inline
device_type device_type_from_str(const char *str)
{
	if (strlen(str) < 2)
		elog(ERROR, "unknown input device_type: %s", str);

	switch (str[0])
	{
		case 'b': if (strcmp(str, "bot") == 0) return BOT;
		case 'c': if (strcmp(str, "console") == 0) return CONSOLE;
		case 'i': if (strcmp(str, "ipod") == 0) return IPOD;
                [...]
        }

// error branch
        elog(ERROR, "unknown input device_type: %s", str);

	return 0; //make compiler happy
}
```

i.e. completely removing the call to `check_device_type_num` and have the switch fall through to the error branch (please note I haven't tested this, yet).

**Comment by zeitgeist** [comment]
(the same trick – if it works – could be applied to all the other functions such as `get_device_type_num_*`, too)

**Comment by rapimo** [comment]
duplicate of 498ba153053112d3b3964b86a04c87619135cd03

**Comment by rapimo** [comment]
@zeitgeist I addressed your comment in 0628173

**Comment by rapimo** [comment]
for reference to fix broken rows

```SQL
WITH del AS (
DELETE FROM session_cohorts
WHERE device_type < 'bot'
RETURNING
first_session_date, tracker_id, country, 'tv'::device_type, os_name, sandbox, impression_based, reattributed,
daily_session_cohort,
weekly_session_cohort,
monthly_session_cohort,
daily_retention_cohort,
weekly_retention_cohort,
monthly_retention_cohort,
daily_time_spent_cohort,
weekly_time_spent_cohort,
monthly_time_spent_cohort,
users
)
UPDATE session_cohorts a
SET
daily_session_cohort = COALESCE(a.daily_session_cohort + b.daily_session_cohort, a.daily_session_cohort, b.daily_session_cohort),
weekly_session_cohort = COALESCE(a.weekly_session_cohort + b.weekly_session_cohort, a.weekly_session_cohort, b.weekly_session_cohort),
monthly_session_cohort = COALESCE(a.monthly_session_cohort + b.monthly_session_cohort, a.monthly_session_cohort, b.monthly_session_cohort),
daily_retention_cohort = COALESCE(a.daily_retention_cohort + b.daily_retention_cohort, a.daily_retention_cohort, b.daily_retention_cohort),
weekly_retention_cohort = COALESCE(a.weekly_retention_cohort + b.weekly_retention_cohort, a.weekly_retention_cohort, b.weekly_retention_cohort),
monthly_retention_cohort = COALESCE(a.monthly_retention_cohort + b.monthly_retention_cohort, a.monthly_retention_cohort, b.monthly_retention_cohort),
daily_time_spent_cohort = COALESCE(a.daily_time_spent_cohort + b.daily_time_spent_cohort, a.daily_time_spent_cohort, b.daily_time_spent_cohort),
weekly_time_spent_cohort = COALESCE(a.weekly_time_spent_cohort + b.weekly_time_spent_cohort, a.weekly_time_spent_cohort, b.weekly_time_spent_cohort),
monthly_time_spent_cohort = COALESCE(a.monthly_time_spent_cohort + b.monthly_time_spent_cohort, a.monthly_time_spent_cohort, b.monthly_time_spent_cohort),
users = COALESCE(a.users + b.users, a.users, b.users)
FROM del b
WHERE
a.first_session_date = b.first_session_date AND
a.tracker_id = b.tracker_id AND
a.country = b.country AND
a.device_type = b.device_type AND
a.os_name = b.os_name AND
a.sandbox = b.sandbox AND
a.impression_based = b.impression_based AND
a.reattributed = b.reattributed;

WITH del AS(
DELETE FROM install_kpis i
WHERE device_type < 'bot'
RETURNING tracker_id, country, 'tv'::device_type, os_name, sandbox, impression_based, date, engagement_date,
installs,
reattributions,
limit_ad_tracking_installs,
limit_ad_tracking_reattributions,
punchcard,
reattribution_punchcard,
hour_distribution,
reattribution_hour_distribution
)
UPDATE install_kpis a
SET
installs = COALESCE(a.installs + b.installs, a.installs, b.installs),
reattributions = COALESCE(a.reattributions + b.reattributions, a.reattributions, b.reattributions),
limit_ad_tracking_installs = COALESCE(a.limit_ad_tracking_installs + b.limit_ad_tracking_installs, a.limit_ad_tracking_installs, b.limit_ad_tracking_installs),
limit_ad_tracking_reattributions = COALESCE(a.limit_ad_tracking_reattributions + b.limit_ad_tracking_reattributions, a.limit_ad_tracking_reattributions, b.limit_ad_tracking_reattributions),
punchcard = COALESCE(a.punchcard + b.punchcard, a.punchcard, b.punchcard),
reattribution_punchcard = COALESCE(a.reattribution_punchcard + b.reattribution_punchcard, a.reattribution_punchcard, b.reattribution_punchcard),
hour_distribution = COALESCE(a.hour_distribution + b.hour_distribution, a.hour_distribution, b.hour_distribution),
reattribution_hour_distribution = COALESCE(a.reattribution_hour_distribution + b.reattribution_hour_distribution, a.reattribution_hour_distribution, b.reattribution_hour_distribution)
FROM del b
WHERE
a.tracker_id = b.tracker_id AND
a.country = b.country AND
a.device_type = b.device_type AND
a.os_name = b.os_name AND
a.sandbox = b.sandbox AND
a.impression_based = b.impression_based AND
a.date = b.date AND
a.engagement_date = b.engagement_date;
```

**Pull request merged**
